### ISSUE TITLE
Editing Actions for an event incomplete?

### ISSUE THREAD

**Issue by kintrupf** [vitas/beaconloc#11]
Editing the properties of an action for an event seems to be incomplete.
Selecting an App for "Start application" or entering an URL for "Open URL" and such is not possible.

**Comment by vitas** [comment]
it should work, if you click on param it should open popup window for edit

**Comment by kintrupf** [comment]
Yes, it does. But adding internal package names for apps that way is a bit cumbersome, a selection of installed apps would have been nice ;-)
