### ISSUE TITLE
Failed to resolve: support-compat

### ISSUE THREAD

**Issue by niravtopsy** [vitas/beaconloc#26]
I  download this code and open in my android studio but getting this error , try to solve many but not solve.

Failed to resolve: support-compat

My Android studio version is : 3.2.1 stable

**Comment by vitas** [comment]
Please, provide full stack of the error. I use 3.2.1 but do not have the issue

**Comment by niravtopsy** [comment]
![screenshot from 2018-10-31 10-38-25](https://user-images.githubusercontent.com/31342060/47767333-304b2a80-dcf9-11e8-9233-a980f6798333.png)

above are screen shot of my error.

I clean project, invalidate cache and restart , remove .gradle file and build file and build again but not work.

**Comment by niravtopsy** [comment]
Following are the image of my error, there no more details on it. i clear project, build , invalidate restart,
remove .gradle , build folder and build again but same error.

![error](https://user-images.githubusercontent.com/31342060/47767474-cd0dc800-dcf9-11e8-822f-4cf5ace8a7a1.jpg)

**Comment by niravtopsy** [comment]
Hello vitas, i am solving this error by downgrading version of  buildToolsVersion and com.android.tools.build:gradle. thanks for your quick reply, this is close now.
