### ISSUE TITLE
OpenBeacon supported?

### ISSUE THREAD

**Issue by davidhedlund** [vitas/beaconloc#4]
Beacon Locator's [F-droid page](https://f-droid.org/repository/browse/?fdfilter=Trigger&fdid=com.samebits.beacon.locator) says:

> Scan, locate and track Bluetooth LE beacons (Eddystone, iBeacons or AltBeacons) allows you to define actions that will be triggered when a specified event occurs.

Can OpenBeacon also be used?

**Comment by vitas** [comment]
What OpenBeacon spec do you mean?

**Comment by davidhedlund** [comment]
@vitas Should OpenBeacon be added to "(Eddystone, iBeacons or AltBeacons)"?

**Comment by vitas** [comment]
Hi David,
I do not know. the app can scan beacons what are supported by altbeacon
library. I do not know if OpenBeacon is supported. I know nothing about
Open Beacon and never seen hardware build by this specification. Eddystone
is open spec released by google..Who is behand OpenBeacon and where to find
info about it?

2016-11-16 16:56 GMT+01:00 David Hedlund <notifications@github.com>:

**Comment by davidhedlund** [comment]
@vitas http://www.openbeacon.org/

**Comment by vitas** [comment]
thanks fro the link i can confirm it is not supported...

2016-11-16 17:18 GMT+01:00 David Hedlund <notifications@github.com>:

**Comment by davidhedlund** [comment]
@vitas 

> i can confirm it is not supported

Thanks for the confirmation. Can you please add that to https://f-droid.org/repository/browse/?fdfilter=Trigger&fdid=com.samebits.beacon.locator ?

**Comment by vitas** [comment]
Sorry, I cannot. i did not add the app to that catalog

2016-11-16 20:24 GMT+01:00 David Hedlund <notifications@github.com>:

**Comment by davidhedlund** [comment]
@vitas Do you allow the admins of f-droid to do it for you?

**Comment by vitas** [comment]
I have no idea who added the app there, did not get any requests or permissions either

**Comment by davidhedlund** [comment]
@vitas Are you the original author of OpenBeacon?

**Comment by vitas** [comment]
I'm author of this beacon locator application, have nothing to do with
OpenBeacon

2016-11-18 5:17 GMT+01:00 David Hedlund <notifications@github.com>:

**Comment by davidhedlund** [comment]
@vitas Sorry, that is what I was going to ask.
