### ISSUE TITLE
Beacon continuously enters/leaves region

### ISSUE THREAD

**Issue by sjcliffe** [vitas/beaconloc#6]
I have some Estimote beacons and am using this App to send MQTT messages via Tasker when beacons enter and leave regions. I'm noticing that when the phone is near a beacon it comes & goes constantly. 

For example, my phone sits on a wireless charger on my bedside table overnight and is approximately 1m from a beacon. Here is an extract from my MQTT log showing this behaviour:

2016-11-16 01:16:02 /Beacon/Ice: ON
2016-11-16 01:16:51 /Beacon/Ice: OFF
2016-11-16 01:17:06 /Beacon/Ice: ON
2016-11-16 01:21:48 /Beacon/Ice: OFF
2016-11-16 01:21:54 /Beacon/Ice: ON
2016-11-16 01:26:50 /Beacon/Ice: OFF
2016-11-16 01:32:02 /Beacon/Ice: ON
2016-11-16 01:36:50 /Beacon/Ice: OFF
2016-11-16 01:36:53 /Beacon/Ice: ON
2016-11-16 01:40:59 /Beacon/Ice: OFF
2016-11-16 01:42:12 /Beacon/Ice: ON
2016-11-16 01:46:00 /Beacon/Ice: OFF

Note: "ON" corresponds to entering the region, "OFF" leaving it.

**Comment by vitas** [comment]
Hi,
do you know advertisement frequency of the beacon ?

**Comment by sjcliffe** [comment]
Advertising interval is 950 ms & broadcast power is set to provide a max range of about 7m.

**Comment by vitas** [comment]
Hi,
i have attached new version of the app, try it out, hope it helps

Regards, vitali

2016-11-15 23:21 GMT+01:00 Steve Cliffe <notifications@github.com>:

**Comment by vitas** [comment]
published new version in relea. thanksse section, please try out

**Comment by sjcliffe** [comment]
Thanks for the prompt response! I'll try it out tonight.

**Comment by sjcliffe** [comment]
I still have this issue with 1.0.9

**Comment by vitas** [comment]
very strange, found similar issue
https://github.com/AltBeacon/android-beacon-library/issues/209

**Comment by sjcliffe** [comment]
And this one using the Estimote SDK - https://forums.estimote.com/t/monitoring-region-problem/2322/29

I turned off Wifi last night but still see the same issue. 

I don't think this is a problem with your app so feel free to close this issue.
