### ISSUE TITLE
most apps cannot be started on event

### ISSUE THREAD

**Issue by readyblue** [vitas/beaconloc#8]
when setting "ACTION":
Action Type: Start Application
Action Parameter: com.package.name

most application cannot be started by this way.
Is there some limitation or privileges problem?

**Comment by vitas** [comment]
need to investigate, what android version do you have?

**Comment by readyblue** [comment]
Android 5.1.1

**Comment by vitas** [comment]
uploaded new version (1.1.1) tried another approach to start app.

**Comment by readyblue** [comment]
Thank you, I can see it. Can you please upload a builded apk file, so I can test it as soon as possible?

**Comment by vitas** [comment]
done. but i would update via google play

**Comment by readyblue** [comment]
Many Thanks, this version works! Already tested on 3 apps, that does not start before.
