### ISSUE TITLE
Add more than one event to a beacon

### ISSUE THREAD

**Issue by kintrupf** [vitas/beaconloc#9]
Currently I can only select "Enter region" _or_ "Leave region" _or_ "Beacon near you" as event, but not more than one of these. So, for example, for one beacon I cannot add an action for "Enter" and a different action for "Leave".

**Comment by vitas** [comment]
You can add unlimited numbers of actions,  just click on add action button
and add new action, even you can add more than one action with the same
type. Not follow what the problem you have

**Comment by kintrupf** [comment]
I believe I have the latest version from the Play Store (Google does not offer to update the app), and there simply is no add action button that I can see. Where should it be?
![screenshot_20161221-114657](https://cloud.githubusercontent.com/assets/8496344/21386592/ccd5fe18-c773-11e6-8d98-173e841c8153.png)

**Comment by vitas** [comment]
You are in screen where to edit selected action,  you need to go back to
management screen and click add action on beacon, it is create second
action

**Comment by kintrupf** [comment]
Found it :-)
While there is no "add action" per se tapping on the orange "ACTION" works.

**Comment by vitas** [comment]
Great , maybe I have to rename it to add action or like that
